# Generated by Django 5.2.1 on 2025-05-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CV',
            new_name='ModelCV',
        ),
    ]
