# Generated by Django 5.2.1 on 2025-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_cv_modelcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('http_method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=260)),
            ],
        ),
    ]
